[primary]
13.234.186.156

[backup]
13.212.20.230

[all:vars]
ansible_user=ubuntu
# This strictly disables the manual yes/no fingerprint prompt we saw earlier so the automation doesn't freeze
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
